// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:81065654-a80d-4b07-ba5d-02b38c79c4f0",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_sqJ6mgcip",
    "aws_user_pools_web_client_id": "3qfs9dpqpgc5i25m8h06mth6e0",
    "oauth": {
        "domain": "dreamtracker-dtenv.auth.eu-central-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://dreamtrackerapp.com/",
        "redirectSignOut": "https://dreamtrackerapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://4az44zoy7jfwli2uritonvk22a.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
